name: random_access_source
description: A shared interface for common random access data.
version: 4.0.0
repository: https://github.com/flutter-cavalry/random_access_source

environment:
  sdk: ^3.4.4

dependencies:
  web: ^1.1.1

dev_dependencies:
  mgenware_dart_lints: ^8.0.0
  test: ^1.24.0
  tmp_path: ^1.3.1
